### PR TITLE
Update .npmignore file 

### PR DESCRIPTION
**Pull request by hildjj**
To not include coverage output, config files, tests, and github actions.

Compressed package size goes from 8.1 kB to 4.0 kB.
Uncompressed package size goes from 36.7 kB to 10.5 kB

to check, run `npm pack --dry-run`

I also updated the dependencies and re-ran all of the tests while I was in there.

### CODE REVIEW

**Comment by hildjj** [comment]
Yikes, you support a bunch of old versions of things.  I'll back out the dependency updates.

**Comment by hildjj** [comment]
I'm going t start over. :)

**Comment by ljharb** [comment]
In the future, please do not make duplicate PRs - that leaves a permanent git ref polluting the repo.

**Comment by hildjj** [comment]
Nod, apologies.

**Pull request closed without merging**
